name: tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  deno-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Run test suite
        run: deno test -A
